M48
; DRILL file {KiCad (6.0.0-0)} date Tuesday, May 30, 2023 at 10:11:56 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-30T22:11:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X5.625Y-4.675
X5.626Y-3.65
X6.319Y-3.878
X6.32Y-4.379
X6.775Y-3.65
X6.775Y-4.675
T0
M30
